RFE: debugging ability
cdiggins/parakeet pull request #9
Opened 2024-11-30 18:54 UTC by Palatis

1. currently it only checks "parser not advancing" in `ZeroOrMoreRule`, `OneOrMoreRule`, and `CountedRule` on a DEBUG build.
however, nuget packages are always build with RELEASE configuration, guarding these checks with `#if DEBUG` make it harder to diagnostic what's going on under the hood - the client code just hit an infinite loop.
thus, just throw the `ParserException` for RELEASE builds.

2. enable the ability to trace rule matching process in an RELEASE build
similar reason to the previous one, nuget packages are build with RELEASE configuration...

well, the assumption that "nuget packages are always RELEASE builds" might not be that correct.
they can be build in DEBUG, however packages on nuget.org are RELEASE, anyway.

2024-11-30 19:22 UTC, cdiggins commented on Parakeet/Rule.cs
> +                if (Debugger.IsAttached && next != null && next.Position <= curr.Position)
The `Debugger.IsAttached` has no real benefit here, if we remove the conditional compilation might as well do the full check and throw an exception. A performance hit will occur.

2024-11-30 19:24 UTC, cdiggins commented on Parakeet/Rule.cs
> -#if DEBUG
This will have a small performance impact. I spent a lot of time trying to make the parser as fast as possible. That said, at this point I think the parser is plenty fast for its primary use case.

2024-11-30 19:25 UTC, cdiggins requested changes
I think that the improvements in usability merit the performance hit. Just remove the "if debugger attached" in the spot where I recommend.

2024-11-30 19:40 UTC, Palatis commented on Parakeet/Rule.cs
> +                if (Debugger.IsAttached && next != null && next.Position <= curr.Position)
i think you're right.

however during normal operation this will just be a null-ness check.

2024-11-30 19:56 UTC, Palatis commented on Parakeet/Rule.cs
> -#if DEBUG
i think it may be worth creating the debug version of these classes, for example `DebugZeroOrMoreRule`, `DebugOneOrMoreRule`, and `DebugCountedRule`, then select which version of the rule instance to create during grammar construction process.
thus we can minimize the performance impact during RELEASE builds.

```CSharp
public class DebugOneOrMoreRule : OneOrMoreRule
{
    public override ParserState MatchImplementation(ParserState state)
    {
        /* same implementation, but check for not advancing */
    }
}

public abstract class Grammar : IGrammar
{
    public virtual IsDebugging => false;
    public Rule OneOrMore(Rule r)
        => IsDebugging ? new DebugOneOrMoreRule(r) : new OneOrMoreRule(r);
}

public static class RuleExtensions
{
    public static Rule OneOrMore(Rule rule, bool debugging = false) ?
        => debugging ? new DebugOneOrMoreRule(rule) : new OneOrMoreRule(rule);
}
```

```CSharp
public sealed class RealGrammar : Grammar
{
#if DEBUG
    public override IsDebugging => true;
#endif

    public Rule S => Node(...);
    public Rule T => Named(OneOrMore(S));
    public Rule R => Named(T.OneOrMore(IsDebugging));
}
```

something like that.

2024-11-30 20:02 UTC, Palatis commented on Parakeet/Rule.cs
> +            : this(CharsToTable(chars))
weird, i don't see those line-ending whitespace diffs on my local tree...

wait, i'll fix that.

2024-11-30 20:18 UTC, Palatis commented
yeah this looks more like it.
hate mixed line-endings...

2024-12-02 16:29 UTC, cdiggins approved these changes
Good job, thanks.

2024-12-02 16:36 UTC, merged